document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("     <link rel=\'stylesheet\' href=\'home.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <!-- header start -->");
document.writeln("    <div class=\'header w\'>");
document.writeln("        <div class=\'logo\'>");
document.writeln("            <h2></h2>");
document.writeln("            <img src=\'name.png\' alt=\'name\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav\'>");
document.writeln("            <ul>");
document.writeln("                <li>");
document.writeln("                    <a href=\'https://weibo.com/u/5878659096\' target=\'_blank\'>");
document.writeln("                        <img src=\'weibo.png\' width=\'37\' height=\'26\'>");
document.writeln("                    </a>");
document.writeln("                    ");
document.writeln("                </li>");
document.writeln("                <li><a href=\'https://www.instagram.com/aliiiya_1011\' target=\'_blank\'>");
document.writeln("                        <img src=\'ins.png\' width=\'35\' height=\'26\'>        ");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("                <li><a href=\'mailto:birdy10113333@163.com\' target=\'_blank\'>");
document.writeln("                        <img src=\'mail.png\' width=\'35\' height=\'26\'>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\'menu\'>");
document.writeln("            <ul>");
document.writeln("                <li><a href=\'index.html\'>HOME</a></li>");
document.writeln("                <li><a href=\'2 resume.html\'>RESUME</a></li>");
document.writeln("                <li><a href=\'3 works.html\'>WORKS</a></li>");
document.writeln("                <li><a href=\'4 contact.html\'>CONTACT</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!-- header end -->");
document.writeln("</body>");
document.writeln("</html>");
